/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as OrariRouteImport } from './routes/orari'
import { Route as AuthenticatedArchivioRouteImport } from './routes/_authenticated/archivio'
import { Route as AuthenticatedFissiRouteImport } from './routes/_authenticated/fissi'
import { Route as AuthenticatedGestioneRouteImport } from './routes/_authenticated/gestione'
import { Route as AuthenticatedImpostazioniRouteImport } from './routes/_authenticated/impostazioni'
import { Route as AuthenticatedOrariGestioneRouteImport } from './routes/_authenticated.orari-gestione'
import { Route as AuthenticatedPrezziRouteImport } from './routes/_authenticated/prezzi'
import { Route as AuthenticatedSettimanaRouteImport } from './routes/_authenticated/settimana'
import { Route as AuthenticatedStatisticheRouteImport } from './routes/_authenticated/statistiche'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const OrariRoute = OrariRouteImport.update({
  id: '/orari',
  path: '/orari',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedArchivioRoute = AuthenticatedArchivioRouteImport.update({
  id: '/archivio',
  path: '/archivio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFissiRoute = AuthenticatedFissiRouteImport.update({
  id: '/fissi',
  path: '/fissi',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGestioneRoute = AuthenticatedGestioneRouteImport.update({
  id: '/gestione',
  path: '/gestione',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImpostazioniRoute =
  AuthenticatedImpostazioniRouteImport.update({
    id: '/impostazioni',
    path: '/impostazioni',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrariGestioneRoute =
  AuthenticatedOrariGestioneRouteImport.update({
    id: '/orari-gestione',
    path: '/orari-gestione',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPrezziRoute = AuthenticatedPrezziRouteImport.update({
  id: '/prezzi',
  path: '/prezzi',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettimanaRoute = AuthenticatedSettimanaRouteImport.update({
  id: '/settimana',
  path: '/settimana',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStatisticheRoute =
  AuthenticatedStatisticheRouteImport.update({
    id: '/statistiche',
    path: '/statistiche',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/menu': typeof MenuRoute
  '/orari': typeof OrariRoute
  '/archivio': typeof AuthenticatedArchivioRoute
  '/fissi': typeof AuthenticatedFissiRoute
  '/gestione': typeof AuthenticatedGestioneRoute
  '/impostazioni': typeof AuthenticatedImpostazioniRoute
  '/orari-gestione': typeof AuthenticatedOrariGestioneRoute
  '/prezzi': typeof AuthenticatedPrezziRoute
  '/settimana': typeof AuthenticatedSettimanaRoute
  '/statistiche': typeof AuthenticatedStatisticheRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/menu': typeof MenuRoute
  '/orari': typeof OrariRoute
  '/archivio': typeof AuthenticatedArchivioRoute
  '/fissi': typeof AuthenticatedFissiRoute
  '/gestione': typeof AuthenticatedGestioneRoute
  '/impostazioni': typeof AuthenticatedImpostazioniRoute
  '/orari-gestione': typeof AuthenticatedOrariGestioneRoute
  '/prezzi': typeof AuthenticatedPrezziRoute
  '/settimana': typeof AuthenticatedSettimanaRoute
  '/statistiche': typeof AuthenticatedStatisticheRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/menu': typeof MenuRoute
  '/orari': typeof OrariRoute
  '/_authenticated/archivio': typeof AuthenticatedArchivioRoute
  '/_authenticated/fissi': typeof AuthenticatedFissiRoute
  '/_authenticated/gestione': typeof AuthenticatedGestioneRoute
  '/_authenticated/impostazioni': typeof AuthenticatedImpostazioniRoute
  '/_authenticated/orari-gestione': typeof AuthenticatedOrariGestioneRoute
  '/_authenticated/prezzi': typeof AuthenticatedPrezziRoute
  '/_authenticated/settimana': typeof AuthenticatedSettimanaRoute
  '/_authenticated/statistiche': typeof AuthenticatedStatisticheRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/menu'
    | '/orari'
    | '/archivio'
    | '/fissi'
    | '/gestione'
    | '/impostazioni'
    | '/orari-gestione'
    | '/prezzi'
    | '/settimana'
    | '/statistiche'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/menu'
    | '/orari'
    | '/archivio'
    | '/fissi'
    | '/gestione'
    | '/impostazioni'
    | '/orari-gestione'
    | '/prezzi'
    | '/settimana'
    | '/statistiche'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/menu'
    | '/orari'
    | '/_authenticated/archivio'
    | '/_authenticated/fissi'
    | '/_authenticated/gestione'
    | '/_authenticated/impostazioni'
    | '/_authenticated/orari-gestione'
    | '/_authenticated/prezzi'
    | '/_authenticated/settimana'
    | '/_authenticated/statistiche'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  MenuRoute: typeof MenuRoute
  OrariRoute: typeof OrariRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orari': {
      id: '/orari'
      path: '/orari'
      fullPath: '/orari'
      preLoaderRoute: typeof OrariRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/archivio': {
      id: '/_authenticated/archivio'
      path: '/archivio'
      fullPath: '/archivio'
      preLoaderRoute: typeof AuthenticatedArchivioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fissi': {
      id: '/_authenticated/fissi'
      path: '/fissi'
      fullPath: '/fissi'
      preLoaderRoute: typeof AuthenticatedFissiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gestione': {
      id: '/_authenticated/gestione'
      path: '/gestione'
      fullPath: '/gestione'
      preLoaderRoute: typeof AuthenticatedGestioneRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/impostazioni': {
      id: '/_authenticated/impostazioni'
      path: '/impostazioni'
      fullPath: '/impostazioni'
      preLoaderRoute: typeof AuthenticatedImpostazioniRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orari-gestione': {
      id: '/_authenticated/orari-gestione'
      path: '/orari-gestione'
      fullPath: '/orari-gestione'
      preLoaderRoute: typeof AuthenticatedOrariGestioneRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prezzi': {
      id: '/_authenticated/prezzi'
      path: '/prezzi'
      fullPath: '/prezzi'
      preLoaderRoute: typeof AuthenticatedPrezziRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settimana': {
      id: '/_authenticated/settimana'
      path: '/settimana'
      fullPath: '/settimana'
      preLoaderRoute: typeof AuthenticatedSettimanaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/statistiche': {
      id: '/_authenticated/statistiche'
      path: '/statistiche'
      fullPath: '/statistiche'
      preLoaderRoute: typeof AuthenticatedStatisticheRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedArchivioRoute: typeof AuthenticatedArchivioRoute
  AuthenticatedFissiRoute: typeof AuthenticatedFissiRoute
  AuthenticatedGestioneRoute: typeof AuthenticatedGestioneRoute
  AuthenticatedImpostazioniRoute: typeof AuthenticatedImpostazioniRoute
  AuthenticatedOrariGestioneRoute: typeof AuthenticatedOrariGestioneRoute
  AuthenticatedPrezziRoute: typeof AuthenticatedPrezziRoute
  AuthenticatedSettimanaRoute: typeof AuthenticatedSettimanaRoute
  AuthenticatedStatisticheRoute: typeof AuthenticatedStatisticheRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedArchivioRoute: AuthenticatedArchivioRoute,
  AuthenticatedFissiRoute: AuthenticatedFissiRoute,
  AuthenticatedGestioneRoute: AuthenticatedGestioneRoute,
  AuthenticatedImpostazioniRoute: AuthenticatedImpostazioniRoute,
  AuthenticatedOrariGestioneRoute: AuthenticatedOrariGestioneRoute,
  AuthenticatedPrezziRoute: AuthenticatedPrezziRoute,
  AuthenticatedSettimanaRoute: AuthenticatedSettimanaRoute,
  AuthenticatedStatisticheRoute: AuthenticatedStatisticheRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  MenuRoute: MenuRoute,
  OrariRoute: OrariRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
