/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedArchivioRouteImport } from './routes/_authenticated/archivio'
import { Route as AuthenticatedFissiRouteImport } from './routes/_authenticated/fissi'
import { Route as AuthenticatedImpostazioniRouteImport } from './routes/_authenticated/impostazioni'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedArchivioRoute = AuthenticatedArchivioRouteImport.update({
  id: '/archivio',
  path: '/archivio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFissiRoute = AuthenticatedFissiRouteImport.update({
  id: '/fissi',
  path: '/fissi',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImpostazioniRoute =
  AuthenticatedImpostazioniRouteImport.update({
    id: '/impostazioni',
    path: '/impostazioni',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/menu': typeof MenuRoute
  '/archivio': typeof AuthenticatedArchivioRoute
  '/fissi': typeof AuthenticatedFissiRoute
  '/impostazioni': typeof AuthenticatedImpostazioniRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/menu': typeof MenuRoute
  '/archivio': typeof AuthenticatedArchivioRoute
  '/fissi': typeof AuthenticatedFissiRoute
  '/impostazioni': typeof AuthenticatedImpostazioniRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/menu': typeof MenuRoute
  '/_authenticated/archivio': typeof AuthenticatedArchivioRoute
  '/_authenticated/fissi': typeof AuthenticatedFissiRoute
  '/_authenticated/impostazioni': typeof AuthenticatedImpostazioniRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/menu' | '/archivio' | '/fissi' | '/impostazioni'
  fileRoutesByTo: FileRoutesByTo
  to: '/auth' | '/menu' | '/archivio' | '/fissi' | '/impostazioni' | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/menu'
    | '/_authenticated/archivio'
    | '/_authenticated/fissi'
    | '/_authenticated/impostazioni'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  MenuRoute: typeof MenuRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/archivio': {
      id: '/_authenticated/archivio'
      path: '/archivio'
      fullPath: '/archivio'
      preLoaderRoute: typeof AuthenticatedArchivioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fissi': {
      id: '/_authenticated/fissi'
      path: '/fissi'
      fullPath: '/fissi'
      preLoaderRoute: typeof AuthenticatedFissiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/impostazioni': {
      id: '/_authenticated/impostazioni'
      path: '/impostazioni'
      fullPath: '/impostazioni'
      preLoaderRoute: typeof AuthenticatedImpostazioniRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedArchivioRoute: typeof AuthenticatedArchivioRoute
  AuthenticatedFissiRoute: typeof AuthenticatedFissiRoute
  AuthenticatedImpostazioniRoute: typeof AuthenticatedImpostazioniRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedArchivioRoute: AuthenticatedArchivioRoute,
  AuthenticatedFissiRoute: AuthenticatedFissiRoute,
  AuthenticatedImpostazioniRoute: AuthenticatedImpostazioniRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  MenuRoute: MenuRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
